spring:
  config:
    import: "classpath:env.properties"
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

application:
  security:
    jwt:
      secret_key: ${application.security.jwt.secret_key}
      expiration: ${application.security.jwt.expiration}
      refresh-token:
        expiration: ${application.security.jwt.refresh_token.expiration}
      cookie:
        jwt_cookie_name: ${application.security.jwt.cookie.jwt_cookie_name}
        jwt_refresh_cookie_name: ${application.security.jwt.cookie.jwt_refresh_cookie_name}
        max_age: ${application.security.jwt.cookie.max_age}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-doc
    enabled: true