spring:
    application:
        name: upwork
    profiles:
        active: dev
debug: true
logging:
    level:
        org.springframework.boot.autoconfigure: ERROR
        org.springframework.core: ERROR